import AppSidebar from '@/components/admin/AppSidebar';
import Header from '@/components/admin/Header';
import { SidebarProvider } from '@/components/ui/sidebar';
import { Toaster } from '@/components/ui/sonner';
import React from 'react'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
  return (
    <SidebarProvider>
      <div className="flex h-screen w-screen overflow-hidden">
        <AppSidebar className="" />
        <div className="flex-1 flex flex-col">
          <Header className="" />
          <main className=" overflow-auto p-4">
            {children}
            <Toaster/>
          </main>
        </div>
      </div>
    </SidebarProvider>
  );
}